# data.py

_MOCK_RESTAURANTS_DB = {
    "rest001": {"name": "The Pizza Place", "cuisine": "Italian", "avg_rating": 4.5, "city": "Metroville"},
    "rest002": {"name": "Burger Barn", "cuisine": "American", "avg_rating": 4.2, "city": "Metroville"},
    "rest003": {"name": "Sushi Central", "cuisine": "Japanese", "avg_rating": 4.8, "city": "Metroville"},
    "rest004": {"name": "Curry Kingdom", "cuisine": "Indian", "avg_rating": 4.6, "city": "Suburbia"},
    "rest005": {"name": "Salad Sensations", "cuisine": "Healthy", "avg_rating": 4.3, "city": "Metroville"},
    "rest006": {"name": "Taco Town", "cuisine": "Mexican", "avg_rating": 4.0, "city": "Suburbia"},
    "rest007": {"name": "Noodle House", "cuisine": "Asian Fusion", "avg_rating": 4.7, "city": "Metroville"},
    "rest008": {"name": "Sweet Treats Bakery", "cuisine": "Desserts", "avg_rating": 4.9, "city": "Metroville"},
}

_MOCK_DELIVERY_AGENTS_DB = {
    "agent01": {"name": "Ravi Kumar", "vehicle_type": "Motorbike", "rating": 4.7, "current_zone": "Metroville North"},
    "agent02": {"name": "Priya Sharma", "vehicle_type": "Scooter", "rating": 4.9, "current_zone": "Metroville South"},
    "agent03": {"name": "Amit Singh", "vehicle_type": "Bicycle", "rating": 4.5, "current_zone": "Suburbia West"},
    "agent04": {"name": "Deepa Reddy", "vehicle_type": "Motorbike", "rating": 4.8, "current_zone": "Metroville Central"},
}

_MOCK_ORDERS_DB = {
    "ORDZW001": {
        "status": "Order Placed",
        "items": ["Pepperoni Pizza (Large)", "Coke (2L)"],
        "customer_id": "cust001",
        "restaurant_id": "rest001",
        "delivery_address": "123 Main St, Metroville, 12345",
        "delivery_agent_id": None,
        "order_total": 25.99,
        "payment_method": "Credit Card",
        "estimated_delivery_time": "30-40 mins",
        "special_instructions": "Extra cheese on pizza."
    },
    "ORDZW002": {
        "status": "Out for Delivery",
        "items": ["Classic Cheeseburger", "Fries (Large)"],
        "customer_id": "cust002",
        "restaurant_id": "rest002",
        "delivery_address": "456 Oak Ave, Metroville, 12346",
        "delivery_agent_id": "agent01",
        "order_total": 18.50,
        "payment_method": "PayPal",
        "estimated_delivery_time": "10-15 mins remaining",
        "special_instructions": "No pickles on burger."
    },
    "ORDZW003": {
        "status": "Delivered",
        "items": ["Salmon Sushi Set", "Miso Soup"],
        "customer_id": "cust001",
        "restaurant_id": "rest003",
        "delivery_address": "123 Main St, Metroville, 12345",
        "delivery_agent_id": "agent02",
        "order_total": 32.75,
        "payment_method": "Credit Card",
        "estimated_delivery_time": "Delivered 5 mins ago",
        "special_instructions": None
    },
    "ORDZW004": {
        "status": "Cancelled",
        "items": ["Chicken Tikka Masala", "Naan Bread"],
        "customer_id": "cust003",
        "restaurant_id": "rest004",
        "delivery_address": "789 Pine Rd, Suburbia, 54321",
        "delivery_agent_id": None,
        "order_total": 22.00,
        "payment_method": "COD",
        "estimated_delivery_time": None,
        "special_instructions": "Make it spicy."
    },
    "ORDZW005": {
        "status": "Restaurant Preparing",
        "items": ["Caesar Salad (Chicken)", "Iced Tea"],
        "customer_id": "cust004",
        "restaurant_id": "rest005",
        "delivery_address": "101 Maple Dr, Metroville, 12347",
        "delivery_agent_id": None,
        "order_total": 15.25,
        "payment_method": "Zwigato Wallet",
        "estimated_delivery_time": "40-50 mins",
        "special_instructions": "Dressing on the side."
    },
    "ORDZW006": {
        "status": "Delivered",
        "items": ["Beef Tacos (3)", "Guacamole & Chips"],
        "customer_id": "cust005",
        "restaurant_id": "rest006",
        "delivery_address": "222 Birch Ln, Suburbia, 54322",
        "delivery_agent_id": "agent03",
        "order_total": 19.80,
        "payment_method": "Credit Card",
        "estimated_delivery_time": "Delivered 20 mins ago",
        "special_instructions": "Extra hot sauce."
    },
    "ORDZW007": {
        "status": "Out for Delivery",
        "items": ["Pad Thai (Shrimp)"],
        "customer_id": "cust002",
        "restaurant_id": "rest007",
        "delivery_address": "456 Oak Ave, Metroville, 12346",
        "delivery_agent_id": "agent04",
        "order_total": 16.50,
        "payment_method": "PayPal",
        "estimated_delivery_time": "5-10 mins remaining",
        "special_instructions": "No peanuts."
    },
    "ORDZW008": {
        "status": "Delivered",
        "items": ["Chocolate Lava Cake", "Vanilla Ice Cream (Scoop)"],
        "customer_id": "cust006",
        "restaurant_id": "rest008",
        "delivery_address": "333 Willow Cr, Metroville, 12348",
        "delivery_agent_id": "agent01",
        "order_total": 12.00,
        "payment_method": "Debit Card",
        "estimated_delivery_time": "Delivered 1 hour ago",
        "special_instructions": None
    },
    "ORDZW009": {
        "status": "Order Placed",
        "items": ["Margherita Pizza (Medium)", "Garlic Bread"],
        "customer_id": "cust007",
        "restaurant_id": "rest001",
        "delivery_address": "414 Cedar Pl, Suburbia, 54323",
        "delivery_agent_id": None,
        "order_total": 20.50,
        "payment_method": "Credit Card",
        "estimated_delivery_time": "35-45 mins",
        "special_instructions": "Thin crust please."
    },
    "ORDZW010": {
        "status": "Issue Reported",
        "items": ["Veggie Burger", "Sweet Potato Fries"],
        "customer_id": "cust002",
        "restaurant_id": "rest002",
        "delivery_address": "456 Oak Ave, Metroville, 12346",
        "delivery_agent_id": "agent02",
        "order_total": 17.00,
        "payment_method": "PayPal",
        "estimated_delivery_time": "Resolved",
        "special_instructions": "Customer reported missing fries, partial refund processed."
    },
    "ORDZW011": {
        "status": "Awaiting Rider Assignment",
        "items": ["California Roll", "Edamame"],
        "customer_id": "cust008",
        "restaurant_id": "rest003",
        "delivery_address": "505 Spruce St, Metroville, 12349",
        "delivery_agent_id": None,
        "order_total": 24.00,
        "payment_method": "Zwigato Wallet",
        "estimated_delivery_time": "45-55 mins",
        "special_instructions": "Extra ginger and wasabi."
    },
    "ORDZW012": {
        "status": "Payment Failed",
        "items": ["Butter Chicken", "Garlic Naan (2)"],
        "customer_id": "cust009",
        "restaurant_id": "rest004",
        "delivery_address": "606 Redwood Ave, Suburbia, 54324",
        "delivery_agent_id": None,
        "order_total": 28.50,
        "payment_method": "Credit Card",
        "estimated_delivery_time": None,
        "special_instructions": "Mild spice level."
    },
    "ORDZW013": {
        "status": "Delivered",
        "items": ["Greek Salad", "Hummus with Pita"],
        "customer_id": "cust010",
        "restaurant_id": "rest005",
        "delivery_address": "707 Elm Rd, Metroville, 12350",
        "delivery_agent_id": "agent03",
        "order_total": 18.75,
        "payment_method": "COD",
        "estimated_delivery_time": "Delivered 30 mins ago",
        "special_instructions": None
    },
    "ORDZW014": {
        "status": "Restaurant Preparing",
        "items": ["Chicken Burrito Bowl"],
        "customer_id": "cust011",
        "restaurant_id": "rest006",
        "delivery_address": "808 Aspen Ct, Suburbia, 54325",
        "delivery_agent_id": None,
        "order_total": 14.99,
        "payment_method": "Debit Card",
        "estimated_delivery_time": "30-40 mins",
        "special_instructions": "No beans, add extra salsa."
    },
    "ORDZW015": {
        "status": "Out for Delivery",
        "items": ["Ramen (Tonkotsu)", "Gyoza (Pork)"],
        "customer_id": "cust012",
        "restaurant_id": "rest007",
        "delivery_address": "909 Fir Way, Metroville, 12351",
        "delivery_agent_id": "agent04",
        "order_total": 29.20,
        "payment_method": "Credit Card",
        "estimated_delivery_time": "15-20 mins remaining",
        "special_instructions": "Extra noodles."
    },
    "ORDZW016": {
        "status": "Delivered",
        "items": ["Red Velvet Cupcake (Box of 4)"],
        "customer_id": "cust013",
        "restaurant_id": "rest008",
        "delivery_address": "111 Juniper Pl, Suburbia, 54326",
        "delivery_agent_id": "agent01",
        "order_total": 16.00,
        "payment_method": "Zwigato Wallet",
        "estimated_delivery_time": "Delivered 45 mins ago",
        "special_instructions": "Happy Birthday message on box."
    },
    "ORDZW017": {
        "status": "Cancelled by Restaurant",
        "items": ["Supreme Pizza (Family Size)"],
        "customer_id": "cust014",
        "restaurant_id": "rest001",
        "delivery_address": "222 Sycamore Dr, Metroville, 12352",
        "delivery_agent_id": None,
        "order_total": 35.50,
        "payment_method": "Credit Card",
        "estimated_delivery_time": None,
        "special_instructions": "Sorry, restaurant is out of a key ingredient."
    },
    "ORDZW018": {
        "status": "Order Placed",
        "items": ["Double Bacon Cheeseburger Meal (Large)"],
        "customer_id": "cust015",
        "restaurant_id": "rest002",
        "delivery_address": "333 Magnolia Ave, Suburbia, 54327",
        "delivery_agent_id": None,
        "order_total": 21.75,
        "payment_method": "PayPal",
        "estimated_delivery_time": "40-50 mins",
        "special_instructions": "Extra crispy bacon."
    },
    "ORDZW019": {
        "status": "Awaiting Rider Assignment",
        "items": ["Tuna Sashimi", "Seaweed Salad"],
        "customer_id": "cust016",
        "restaurant_id": "rest003",
        "delivery_address": "444 Poplar St, Metroville, 12353",
        "delivery_agent_id": None,
        "order_total": 27.80,
        "payment_method": "Debit Card",
        "estimated_delivery_time": "35-45 mins",
        "special_instructions": None
    },
    "ORDZW020": {
        "status": "Delivered",
        "items": ["Paneer Butter Masala", "Rice", "Mango Lassi"],
        "customer_id": "cust017",
        "restaurant_id": "rest004",
        "delivery_address": "555 Chestnut Rd, Suburbia, 54328",
        "delivery_agent_id": "agent02",
        "order_total": 30.15,
        "payment_method": "COD",
        "estimated_delivery_time": "Delivered 10 mins ago",
        "special_instructions": "Not too oily please."
    },
    "ORDZW021": {
        "status": "Out for Delivery",
        "items": ["Quinoa Bowl (Vegan)", "Fresh Orange Juice"],
        "customer_id": "cust018",
        "restaurant_id": "rest005",
        "delivery_address": "666 Hemlock Cr, Metroville, 12354",
        "delivery_agent_id": "agent03",
        "order_total": 19.90,
        "payment_method": "Zwigato Wallet",
        "estimated_delivery_time": "5-10 mins remaining",
        "special_instructions": "Ensure cutlery is included."
    },
    "ORDZW022": {
        "status": "Restaurant Preparing",
        "items": ["Fish Tacos (2)", "Chicken Quesadilla"],
        "customer_id": "cust019",
        "restaurant_id": "rest006",
        "delivery_address": "777 Cypress Ln, Suburbia, 54329",
        "delivery_agent_id": None,
        "order_total": 23.40,
        "payment_method": "Credit Card",
        "estimated_delivery_time": "25-35 mins",
        "special_instructions": "Separate containers for tacos and quesadilla."
    },
    "ORDZW023": {
        "status": "Delivered",
        "items": ["Spicy Miso Ramen", "Edamame", "Green Tea"],
        "customer_id": "cust005",
        "restaurant_id": "rest007",
        "delivery_address": "222 Birch Ln, Suburbia, 54322",
        "delivery_agent_id": "agent04",
        "order_total": 26.50,
        "payment_method": "Credit Card",
        "estimated_delivery_time": "Delivered 15 mins ago",
        "special_instructions": "Extra spicy broth."
    }
}

_MOCK_WIKI_DB = {
    "gold membership": "Zwigato Gold offers free delivery on orders over $15 from participating restaurants, exclusive discounts, and priority customer support. It costs $9.99/month or $99/year.",
    "zwigato gold benefits": "Zwigato Gold offers free delivery on orders over $15 from participating restaurants, exclusive discounts, and priority customer support. It costs $9.99/month or $99/year.",
    "zwigato membership": "Zwigato Gold offers free delivery on orders over $15 from participating restaurants, exclusive discounts, and priority customer support. It costs $9.99/month or $99/year.",
    "membership benefits": "Zwigato Gold offers free delivery on orders over $15 from participating restaurants, exclusive discounts, and priority customer support. It costs $9.99/month or $99/year.",   
    "delivery fees": "Delivery fees vary based on distance from the restaurant and current demand. Zwigato Gold members enjoy free delivery on eligible orders. You'll see the exact fee before confirming your order.",
    "cancel order policy": "You can cancel an order free of charge if the restaurant has not yet started preparing it (usually within 5 minutes of placing or while 'Awaiting Rider Assignment'). After the restaurant starts preparing, a cancellation fee may apply or cancellation might not be possible. Check your order status in the app for cancellation options. Orders already 'Out for Delivery' or 'Delivered' cannot be cancelled.",
    "refund policy": "If you receive a wrong item, a damaged order, or if items are missing, please contact Zwigato support within 2 hours of delivery with your order ID and a photo (if applicable). We'll investigate and process refunds or credits accordingly. For issues noted in your order like for ORDZW010, actions like refunds may have already been processed.",
    "minimum order value": "Some restaurants may have a minimum order value for delivery. This will be indicated on the restaurant's page before you add items to your cart.",
    "zwigato for business": "Zwigato offers corporate accounts for businesses looking to provide meal solutions for employees, catering for events, or regular office pantry stocking. Contact corpsales@zwigato.com for more details.",
    "food quality and hygiene": "Zwigato partners with restaurants that adhere to strict food safety and hygiene standards. Our delivery partners are trained for safe food handling. If you have concerns, please report them to support immediately.",
    "estimated delivery times": "Estimated delivery times are calculated based on restaurant preparation time, distance, traffic, and rider availability. While we strive for accuracy, unforeseen circumstances can cause delays.",
    "track my order": "You can track your order in real-time via the Zwigato app or website. You'll see updates from when the restaurant accepts the order to when the delivery agent is on their way.",
    "payment methods accepted": "Zwigato accepts major credit/debit cards (Visa, MasterCard, Amex), PayPal, Zwigato Wallet, and Cash on Delivery (COD) for select orders and locations.",
    "update billing information": "To update your payment methods, go to 'Account Settings' in the Zwigato app or website, then select 'Payment Methods'. You can add, remove, or set a default payment option.",
    "password reset": "If you've forgotten your password, click the 'Forgot Password?' link on the login screen. Enter your registered email address, and we'll send you instructions to reset it.",
    "data privacy policy": "Your privacy is important. Our policy, available at zwigato.com/privacy, explains how we collect, use, and protect your personal information. Zwigato is compliant with relevant data protection regulations.",
    "terms of service": "Our terms of service outline your rights and responsibilities when using Zwigato. You can find them at zwigato.com/terms.",
    "contact support": "For any issues, contact Zwigato support via in-app chat, email at support@zwigato.com, or call 1-800-ZWIGATO (9 AM - 11 PM daily). Please have your order ID ready.",
    "about zwigato": "Zwigato is your friendly neighborhood food delivery service, connecting you with the best local restaurants. Our mission is to deliver delicious food, fast and fresh, right to your doorstep.",
    "how to become a delivery partner": "Interested in riding with Zwigato? Visit zwigato.com/riders to learn about the benefits, requirements, and application process.",
    "list my restaurant on zwigato": "Restaurant owners can expand their reach by partnering with Zwigato. Visit zwigato.com/restaurants for information on how to join our platform.",
    "how to list restaurant on zwigato": "Restaurant owners can expand their reach by partnering with Zwigato. Visit zwigato.com/restaurants for information on how to join our platform.",
    "how to register restaurant on Zwigato": "Restaurant owners can expand their reach by partnering with Zwigato. Visit zwigato.com/restaurants for information on how to join our platform.",
    "patner with Zwigato": "Restaurant owners can expand their reach by partnering with Zwigato. Visit zwigato.com/restaurants for information on how to join our platform.",
    "restaurant on zwigato": "Restaurant owners can expand their reach by partnering with Zwigato. Visit zwigato.com/restaurants for information on how to join our platform.",
    "referral program": "Share your Zwigato referral code with friends! When they place their first order, you both get $5 off your next meal. Find your code in the 'Promotions' section of the app.",
    "allergy information": "Restaurants provide allergy information for their dishes. Please check the item details carefully. For severe allergies, we recommend contacting the restaurant directly before ordering through Zwigato to confirm.",
    "what if my order is late?": "We apologize for any delays. You can track your order's progress in the app. If it's significantly late, please contact Zwigato support for assistance.",
    "rating your order": "After your order is delivered, you can rate the food and the delivery experience. Your feedback helps us and our partners improve!",
    "zwigato wallet": "Zwigato Wallet is a convenient way to pay. Add funds using your preferred payment method and enjoy faster checkouts. Refunds and promotional credits are often issued to your Wallet.",
    "scheduling orders": "Yes, you can schedule orders for a later time or date from select restaurants. Look for the 'Schedule Order' option at checkout.",
    "group orders": "Planning a meal with friends or colleagues? Use our 'Group Order' feature. Share a link, everyone adds their items, and one person checks out. (Feature availability may vary)"
}